### ISSUE TITLE
Add direct GitHub links to corresponding MDX source files on each page

### ISSUE THREAD

**Issue by osslate** [daytonaio/docs#10]
To encourage others to contribute to the docs, we should include a link to the source on GitHub for each documentation page. From there, people can choose to fork this repo and edit the file in a branch using GitHub's web editor, or at the very least, they will know where they can find the content of the doc on their filesystem.

This should be dynamically done with Astro, avoiding a scenario where we need to define the URL manually for each page.

**Comment by osslate** [comment]
Hi [mikimih](https://github.com/mikimih), could you implement the design for the "Edit page" button on each page and open a PR?

<img width="452" alt="image" src="https://github.com/daytonaio/docs/assets/773673/8eb2397d-bf7d-4e7e-a73e-c0140f2af238">

**Comment by ivan-burazin** [comment]
@FilipVecek pinging you as well

**Comment by mikimih** [comment]
@ivan-burazin @osslate 
here is PR:
https://github.com/daytonaio/docs/pull/28
