### ISSUE TITLE
Add AWS CodeCommit git provider entry

### ISSUE THREAD

**Issue by Tpuljak** [daytonaio/docs#109]
https://github.com/daytonaio/daytona/pull/797 added support for AWS CodeCommit to Daytona.

We should add a section to https://www.daytona.io/docs/configuration/git-providers/ outlining how to add it.

**Comment by ivan-burazin** [comment]
Also i note to @stefanicjuraj i would rewrite GIT Providers similar to installation. More specifically that the urls are https://www.daytona.io/docs/configuration/git-providers#github
https://www.daytona.io/docs/configuration/git-providers#bitbucket
and so on.

And on those places you fined end to end the instruction on how to install each.

BTW I am aware there will be a lot of duplicate text, but as a user its is much more straight forward as all I need is on one place.

**Comment by Tpuljak** [comment]
Moved https://github.com/daytonaio/docs/issues/109#issuecomment-2273388599 to a separate issue
