### ISSUE TITLE
Incorrect Redirect for Managing Targets in Documentation

### ISSUE THREAD

**Issue by varshith257** [daytonaio/docs#118]
**Describe the bug**
The documentation link referencing "Managing Targets" is incorrectly directing users to the wrong section of the documentation in Workspaces page.

**To Reproduce**
1. Go to 'Go to [Daytona Workspaces Documentation](https://www.daytona.io/docs/usage/workspaces/#create-a-workspace).'
2. Click on the link of "One Target Configured" in prerequisites.
3. Observe that it directs you to the wrong URL: `https://www.daytona.io/docs/usage/configuration/providers#managing-targets`

**Expected behavior**
The link should correctly direct users to the appropriate section under "Providers" in the documentation. The correct URL should be:
`https://www.daytona.io/docs/configuration/providers/#managing-targets`

**Screenshots**
![image](https://github.com/user-attachments/assets/d2a28100-4eec-4bd1-a7be-7c830b30ca80)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Daytona Version: [e.g. v0.0.1]

**Additional context**
This issue impacts the usability of the documentation by directing users to the wrong section, which can lead to confusion when trying to manage targets. The link needs to be updated to reflect the correct path.

**Comment by Tpuljak** [comment]
@varshith257 thanks for raising the issue. Transferred it here to the docs repo
