### ISSUE TITLE
Docs need i18n

### ISSUE THREAD

**Issue by loveloki** [daytonaio/docs#153]
Are there any plans for i18n now?

I can do the simplified Chinese part.

**Comment by ivan-burazin** [comment]
@loveloki can you elaborate a bit more? How can we help?

**Comment by loveloki** [comment]
@ivan-burazin

This idea came about after I asked a question at salck a few days ago. At that time, @Tpuljak was very patient in explaining various concepts to me and correcting my mistakes. Then the idea came to me.
The main reason for the idea is that for non-native developers, English documents may have problems such as:difficulty in understanding and querying.

If you do want to provide i18n: then
- It may be better to start early in the document rather than add to it later when the content becomes richer.
- How can there be an easy-to-handle way to synchronize document updates? I don't have any good ideas about this.

**Comment by ivan-burazin** [comment]
You mean translate in multiple languages?
If thats so, then this will be in the backlog, as we still need to get the docs at a satisfactory level first.

Thanks
