### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by Tpuljak** [daytonaio/docs#196]
We should add a sitemap to the page so that crawlers have an easier job indexing. This is especially important for search.

**Comment by ivan-burazin** [comment]
@Tpuljak we need to make sure that this sitemap is indexed in the main sitemap as its all one website. this is not a sub domain

**Comment by ivan-burazin** [comment]
not sure. as per sitemap format there should be a main sitmap.xml and it can include others. so we need to properly structure that

cc @fabjanvucina

**Comment by Tpuljak** [comment]
We could have a main sitemap that includes the docs sitemap but the indexing of the search could scrape the docs sitemap only.

**Comment by fabjanvucina** [comment]
This repo already has a sitemap which is included in the sitemap index for our main website.

https://www.daytona.io/sitemap-index.xml
- ...
- https://www.daytona.io/docs/sitemap-index.xml
  - https://www.daytona.io/docs/sitemap-0.xml
    - ...

**Comment by Tpuljak** [comment]
Great. I manually added the sitemap URL to the algolia crawler. I'll close the issue once I confirm that it works.

**Comment by Tpuljak** [comment]
Looks good.
