### ISSUE TITLE
Update navigation items with appropriate icons

### ISSUE THREAD

**Issue by osslate** [daytonaio/docs#20]

**Comment by ivan-burazin** [comment]
@mikimih can you help with this please? thanks

**Comment by mikimih** [comment]
To update the sidebar icon, modify the `sidebar-attr-icon` property in the `astro.config.mjs` file. Replace the current icon name with the desired icon from the `/src/assets/sidebar/` folder.

Example:

```json
{
  "label": "Explanation",
  "items": [
    {
      "label": "What is Daytona?",
      "link": "/explanation/what-is-daytona",
      "attrs": {
        "icon": "git-commit.svg"
      }
    }
  ]
}
```

To change the icon, simply replace `git-commit.svg` with the new icon's name.

**Comment by ivan-burazin** [comment]
> To update the sidebar icon, modify the `sidebar-items-attr-icon` property in the `astro.config.mjs` file. Replace the current icon name with the desired icon from the `/src/assets/sidebar/` folder.
> 
> Example:
> 
> ```json
> {
>   "label": "Explanation",
>   "items": [
>     {
>       "label": "What is Daytona?",
>       "link": "/explanation/what-is-daytona",
>       "attrs": {
>         "icon": "git-commit.svg"
>       }
>     }
>   ]
> }
> ```
> 
> To change the icon, simply replace `git-commit.svg` with the new icon's name.

@osslate there you go
