### ISSUE TITLE
Automate CLI reference doc generation

### ISSUE THREAD

**Issue by osslate** [daytonaio/docs#22]
Currently, the CLI reference is edited manually for each release. It appears possible using Cobra (the CLI framework Daytona uses) to [automate Markdown generation](https://cobra.dev/#generating-documentation-for-your-command) based on the commands/subcommands/flags it knows of at runtime.

Implementing this will allow us to generate precise, accurate CLI reference documentation for each release, and ensure that the docs reflect the exact state of Daytona. Once implemented, it means we will not need to manually edit or change the CLI reference docs for accuracy.

cc: @Tpuljak for implementation ideas

**Comment by Tpuljak** [comment]
Cc @idagelic might have experience with this

**Comment by idagelic** [comment]
Could you open an issue for docs generation in the 'daytona' repo @osslate?
Last time we discussed this, we landed on having the CLI generate the md files on release and push their contents to an S3 bucket, where the docs app would then fetch and display them. Let me know if there is any specific format needed to have it work with any special .md file formatters you're using for the docs, or if a 1:1 command - md file generation is enough for now.

**Comment by Tpuljak** [comment]
I think a better approach would be that they are generated inside the repo. Similar to how we generate the API client.
The docs can then get the content from `URL/tags/<VERSION>`.
This is much cleaner I think.

**Comment by osslate** [comment]
I'm assuming here that Cobra outputs multiple `.md` files for each command. My ideal workflow, if straightforward to implement:

* A script that lives here (`daytonaio/docs`) executed like `./compile-cli-ref 0.17.0` starts with one of two operations:
  1. Spins up a container, pulls the tagged release from `daytonaio/daytona`, executes appropriate commands to extract `.md` files based on the CLI, __OR__
  2. Grabs the `.md` files as a GitHub artifact from the release (e.g. in a tar/zip)
* The script transforms the collection of `.md` files into a publishable `cli.mdx` for user documentation and outputs it to stdout.

The two options yield the same end result, but it depends on whether we want Cobra's `.md` generation to live entirely in the Docs publishing workflow, or have the generation happen as part of `daytonaio/daytona` independently and solely do transformation here. I have no strong opinions either way, so it comes down to your preference.

I'm comfortable to implement the script to transform it how I need once there's a way to grab the `.md` files.

**Comment by Tpuljak** [comment]
I suggest we demo some options next week and see what works best.

**Comment by osslate** [comment]
CLI docs now published on https://download.daytona.io/. Working on a script to ingest these and reformat as needed.

**Comment by Tpuljak** [comment]
@osslate you can check out https://github.com/daytonaio/daytona/pull/609 where you'll see that we added the docs to the repo. You will then be able to get them from [https://github.com/daytonaio/daytona/tree/VERSION/docs](https://github.com/daytonaio/daytona/tree/VERSION/docs)
