### ISSUE TITLE
Create "Installation" icon

### ISSUE THREAD

**Issue by osslate** [daytonaio/docs#33]
Issue to track the design of an Installation icon for the sidebar.

## Context

* https://github.com/daytonaio/docs/pull/25#issuecomment-2136798065
* Icon exists but needs some changes before merging.

cc: @mikimih @filipvecek - feel free to open a PR

**Comment by ivan-burazin** [comment]
@osslate can you share option from the icon family that work here?

**Comment by osslate** [comment]
Fixed in #25
