### ISSUE TITLE
Create "Server" icon

### ISSUE THREAD

**Issue by osslate** [daytonaio/docs#34]
We need an icon for the "Server" sidebar item.

cc: @mikimih @filipvecek

**Comment by ivan-burazin** [comment]
@osslate can you share option from the icon family that work here?

**Comment by mikimih** [comment]
For the "Server" sidebar item, we recommend using the [Server icon from Primer](https://primer.style/foundations/icons/server-16).

**Comment by ivan-burazin** [comment]
Seems this is done https://github.com/daytonaio/docs/pull/38
