### ISSUE TITLE
Text colors light mode

### ISSUE THREAD

**Issue by ivan-burazin** [daytonaio/docs#41]
As per Figma, All text on light mode should be the same (note titles are a different shade)
<img width="603" alt="Screenshot 2024-05-31 at 15 51 57" src="https://github.com/daytonaio/docs/assets/11191224/eee2fe06-4e6d-48a6-b7b2-06a3e663896e">

Currently we have multiple and is barley readable 
<img width="811" alt="Screenshot 2024-05-31 at 15 54 40" src="https://github.com/daytonaio/docs/assets/11191224/40380fe4-d259-4be8-a3af-34f574264be4">

@mikimih

**Comment by mikimih** [comment]
Here is PR: https://github.com/daytonaio/docs/pull/44
