### ISSUE TITLE
Syntax highlighting theme incorrect - Light mode

### ISSUE THREAD

**Issue by ivan-burazin** [daytonaio/docs#42]
Syntax highlighting theme incorrect - Light mode
Current:
<img width="669" alt="Screenshot 2024-05-31 at 16 02 15" src="https://github.com/daytonaio/docs/assets/11191224/2192f8da-7f21-46fe-a5c5-ab3f36c9ac9e">
Figma:
<img width="839" alt="Screenshot 2024-05-31 at 16 01 31" src="https://github.com/daytonaio/docs/assets/11191224/74004a16-d745-49a7-8e50-8a7e51597a49">
@mikimih  Please correct and double check rest of website.

Thanks

**Comment by Swearengen** [comment]
@ivan-burazin where can I find how syntax highlight looks in figma in white theme? where is this screenshot from? I couldn't find it.
Is this the issue just for a bash syntax or other languages are problem also?
I checked how syntax-highlight works and the conclusion is that this is probably some vs code theme and it will be hard to fix it, maybe better to find some other theme.

**Comment by ivan-burazin** [comment]
@Swearengen tagged you in Figma. I believe all syntax highlighting is using one theme. The issue is that on the light theme, the wrong colors are being used.

Please update all styles in Figma, including the screenshot above.
