### ISSUE TITLE
Version in header should have patch version stripped

### ISSUE THREAD

**Issue by osslate** [daytonaio/docs#49]
To facilitate patch versions of the docs (independent from Daytona itself), we should strip the patch version displayed on the website and leave it as `x.y`. After a discussion with @vedranjukic, it appears the patch element of Daytona releases are going to signify bug fixes.

Since Daytona patch versions don't introduce new features or change existing functionality, we can leverage the patch version to signify in-between docs updates and have the website display `0.16`, `0.17`, etc. rather than `0.16.0`, `0.17.1` etc.

**Comment by ivan-burazin** [comment]
@osslate is there a question or can we close this?
