### ISSUE TITLE
Missing broken link validation for PRs

### ISSUE THREAD

**Issue by osslate** [daytonaio/docs#76]
We're not checking for broken links in open PRs. We should add a GitHub Action to check links and anchors.

**Comment by vedranjukic** [comment]
Do you need assistance on this?

**Comment by osslate** [comment]
PR coming shortly!

**Comment by osslate** [comment]
Quick update on this: I've evaluated [Lychee](https://github.com/lycheeverse/lychee), which works really well, but there are changes we need that haven't yet been released. Since I'm not sure when they're planning their next release, I'll probably go with something like htmltest.
