### ISSUE TITLE
```text remove copy icon in production 

### ISSUE THREAD

**Issue by ivan-burazin** [daytonaio/docs#99]
Need to remove the copy button from ```text tag 

<img width="788" alt="Screenshot 2024-08-01 at 19 40 32" src="https://github.com/user-attachments/assets/1e9b0e75-7d02-461a-b34a-c81c925d9485">

**Comment by ivan-burazin** [comment]
@stefanicjuraj Let me know if you can solve this if not can pass it on. Thanks

**Comment by stefanicjuraj** [comment]
Hi @ivan-burazin, I can solve this - will open a pull request with the fix.
